### PR TITLE
Add adoption guidelines and rework README, fixes #6, #7

### LINKED ISSUE #6: Adoption guidelines
I doubt that we will need sth. like this in the near future (of course having such an increased interest would be cool).

Anyways, I just wanted to put my ideas on this topic up here - it will probably be similar to the [Arch guidelines](https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines):

- popularity (this is hard to judge, but I guess GH stars are the best measurement that we have)
  Q: Is there enough interest from the general public, s.t. it's worth maintaining?
- competition
  Q: Is there a similar library with active development out there?
- sponsor
  Q: Is there someone that is willing have an idea at the development process?

### PR DESCRIPTION
**Pull request by wilzbach**
Basically incorporating the feedback from #6 and #7 into the README.
Of course this isn't set into stone & can also be improved upon.

### CODE REVIEW

**Comment by rikkimax** [comment]
Currently the guidelines are conflating best practice with how members of the organization should behave.

If the goal is to help maintain codebases which are in use but don't have enough help to keep it going e.g. pulling PR's, then this PR does not address this.

So here is what we are looking at:

- What do we expect (as best practice for D code)?
- What do you need from us?

A list for best practice (basically what you got already):

- Use some form of CI integration
- Documentation generation e.g. adrdox via CI integration on push
- Don't push straight to repo, fork +PR


A small list for guidelines of members:

- Should we pull if no reply after a week?
- Can we pull smaller changes like docs if they come up
- Do you require a specific set of people to perform maintenance, e.g. specialities or just preference
- Do you have any specific instructions for us?
- Do you want us to approve PR's from your fork?
- Is it not ok for self pulling of PR's?

**Comment by BBasile** [comment]
> Can we pull smaller changes like docs if they come up

Allowed without CI,fix obvious typo etc. Readme changes, etc.

> Should we pull if no reply after a week?

No for new features. Yes for bugfixes that pass CI. That being said there are cases where a bugfix can be pushed and it breaks something that's not yest tested.

> Is it not ok for self pulling of PR's?

Ok if approved. This has been already been done latest 2 weeks. The case of "no reply after a week" makes exception (so a bugfix that passes CI).

**Comment by BBasile** [comment]
Also something i like is what's done in the DUB repository: fixes and new features are pushed in new branches directly in the original repository. Are we allowed to make PR with branches on the official repo rather than on our fork ? I think so. It's easier to test the fix or the new feaure. Because no need to add a new origin.

**Comment by rikkimax** [comment]
The important thing is that the guidelines leave the original authors in control, not us.
We're here to help maintain, making everybody's lives a bit easier.

**Comment by BBasile** [comment]
> leave the original authors in control

Sure for Hackerpilot, but for kiith-sa this strategy is the same as accepting to hit a wall

**Comment by wilzbach** [comment]
Thanks at @BBasile @rikkimax for your ideas and discussion and I have tried to incorporate your feedback to this PR.
As you have seen I'm unfortunately also not that often available and currently our README is nearly blank, so I would appreciate if you pull this if you agree with the main content.
You/we can always add new ideas/answers/guidelines to it afterwards (I guess this will be a continuous process as we gain more experience with this organization).

**Comment by wilzbach** [comment]
> wilzbach commented 12 days ago

Hmm ... So I am now taking action and merging this PR as currently the README is almost blank.
Please feel free to submit edit / improvements to the README ;-)

**Pull request merged**
